server:
  port: 7082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
 metrics:
  enabled: true
 command:
  default:
   execution:
    isolation:
     thread:
       timeoutInMilliseconds: 100000

master:
  datasource:
    url: jdbc:mysql://localhost:3306/inst02
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
